version: '3.3'
#R D MN
services:
  sakila:
    image: mysql_img
    container_name: sakila
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      LANG: C.UTF_8
      MYSQL_DATABASE: 'sakila'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: code_academy_db
    ports:
      - '5432:5432'
    volumes:
      - posgres-db:/var/lib/postgresql

  mongo:
    image: mongodb/mongodb-community-server:5.0.17-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: code_academy_db
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/var/lib/mongo

# Names our volume
volumes:
  mysql-db:
  posgres-db:
  mongo-db: