# Can set active profile using ... application.yaml
#spring.profiles.active=prodProfile2,myCustomProfile

my.custom.environment.property: "default property value"

logging:
  level:
    root: info

# kelias į DB (in memory, ram'uose).
spring:
  datasource:
    url: "jdbc:h2:mem:blog_db"
    # default user
    username: sa
    # default password
    password:

  # schemos iniciavimo scripto vieta
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  # jeigu kas nors netinka duombazeje - tegu Hibernate pataiso automatiskai. Jei viskas OK - tegu neliecia
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# įjungti H2 WEB konsolę
  h2:
    console:
      enabled: true
      # H2 web konsolės adresas (URL)
      path: /h2

# Disable whitelabel error pages
server:
  error:
    whitelabel:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: testProfile
my.custom.environment.property: "testProfile property value"